"""inital creation

Revision ID: d811f330fc6
Revises: None
Create Date: 2013-06-12 15:09:13.655683

"""

# revision identifiers, used by Alembic.
revision = 'd811f330fc6'
down_revision = None

from alembic import op
import sqlalchemy as sa

from spyne.util.sqlalchemy import PGObjectXml

def upgrade():
    op.create_table(
        'examples',
        # following line originally generated by alembic with syntax error
        # sa.Column('a_list', 
        #           sa.PGObjectXml(<class 'spyne.model.complex.Array'>),
        #           nullable=False),
        # it is worth noting it doesn't matter what argument is used here 
        # as the underlying Postgresql type is always "xml" and the class is
        # not used.
        sa.Column('a_list', PGObjectXml(None), nullable=False),
        sa.Column('id', sa.UnicodeText(), nullable=False),
        sa.PrimaryKeyConstraint('id'))

def downgrade():
    op.drop_table('examples')
